

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
          resources: {}
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-config
  
        - name: prometheus-storage-volume
          emptyDir: {}

--- 

apiVersion: v1
kind: Service
metadata:
  name: prometheus
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
  namespace: monitoring
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      name: prometheus
      port: 9090
      targetPort: 9090


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |-
    # my global config
    global:
      scrape_interval: 15s
      evaluation_interval: 30s
      scrape_timeout: "10s"

      #external_labels:
      #  monitor: codelab

    scrape_configs: 
      - job_name: 'Prometheus'
        static_configs:
          - targets: ['localhost:9090']
            labels:
              grupo: 'Prometheus'

      - job_name: 'Node Exporter'         
        static_configs:    
          - targets: ['node-exporter.monitoring.svc.cluster.local:9100']
            labels:
              grupo: 'Node Exporter'

      - job_name: 'Jolokia Exporter'
        static_configs:
          - targets: ['jolokia-exporter.default.svc.cluster.local:9422']
            labels:
              grupo: 'Jolokia Exporter'


