kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080 # Porta do Jenkins
        hostPort: 30080 # Porta do host
        protocol: TCP
      - containerPort: 30778 # Porta do Jolokia
        hostPort: 30778 # Porta do host
        protocol: TCP